version: "3.8"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./resources/reverse-proxy/default.conf:/etc/nginx/default.conf
      - ./resources/reverse-proxy/certs:/etc/ssl/certs
      - ./resources/reverse-proxy/includes:/etc/nginx/includes

  service-registry:
    container_name: service-registry
    build:
      context: service-registry
      dockerfile: Dockerfile
    image: robberdg/service-registry:latest
    ports:
      - 8761:8761
    networks:
      - backend-services

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: robberdg/api-gateway:latest
    ports:
      - 8080:8080
    networks:
      - backend-services
    environment:
      - EUREKA=http://service-registry:8761/eureka

  user-service:
    container_name: user-service
    build:
      context: user-service
      dockerfile: Dockerfile
    image: robberdg/user-service:latest
    expose:
      - 9001
    networks:
      - backend-services
    environment:
      - EUREKA=http://service-registry:8761/eureka

  car-service:
    container_name: car-service
    build:
      context: car-service
      dockerfile: Dockerfile
    image: robberdg/car-service:latest
    expose:
      - 9002
    networks:
      - backend-services
    environment:
      - EUREKA=http://service-registry:8761/eureka

  ride-service:
    container_name: ride-service
    build:
      context: ride-service
      dockerfile: Dockerfile
    image: robberdg/ride-service:latest
    expose:
      - 9003
    networks:
      - backend-services
    environment:
      - EUREKA=http://service-registry:8761/eureka


  billing-service:
    container_name: billing-service
    build:
      context: billing-service
      dockerfile: Dockerfile
    image: robberdg/billing-service:latest
    expose:
      - 9004
    networks:
      - backend-services
    environment:
      - EUREKA=http://service-registry:8761/eureka

networks:
  backend-services:
    driver: bridge