server:
  port: 8080
  ssl:
    enabled: true
    key-alias: tomcat
    key-store-password: password
    key-store: classpath:keyStore.p12
    key-store-type: PKCS12
    key-password: password

spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      httpclient:
        ssl:
          useInsecureTrustManager: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA}

auth0:
  audience: https://bachelorproject/api
