server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth0:
  audience: https://bachelorproject/api
