server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

auth0:
  audience: https://bachelorproject/api
