server:
  port: 9002

spring:
  application:
    name: CAR-SERVICE
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://bachelorproject-db.cxgz8qf6xo0i.eu-west-3.rds.amazonaws.com:3306/cars?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: car_service
    password: E2qhvd&S%H^jRzt24Vfptq*!2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/
  rabbitmq:
    external:
      host: rat.rmq2.cloudamqp.com
      username: iyopjwwd
      password: ntVEoqTWlN38mXwCrhgdHUmDaOwB86N1
    internal:
      host: rat.rmq2.cloudamqp.com
      username: lzufimom
      password: llcqxq_5XuJES-s0hhmiinhDfV3kVCDj
  configurations:
    carRequest:
      expirationTimeInMilliseconds: 10000
    reservation:
      reservationCoolDownInSeconds: 7200

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA:http://localhost:8761/eureka/}

