server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://bachelorproject-db.cxgz8qf6xo0i.eu-west-3.rds.amazonaws.com:3306/users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user_service
    password: 8YC^JfCXwTLHQ9fEGF*WkwtYM
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

