server:
  port: 9004

spring:
  application:
    name: BILLING-SERVICE
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/payments?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: billing_service
    password: Ue^WFJmS7V6t85$3r$v!TYwYK
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/
  rabbitmq:
    external:
      host: rat.rmq2.cloudamqp.com
      username: iyopjwwd
      password: ntVEoqTWlN38mXwCrhgdHUmDaOwB86N1
    internal:
      host: rat.rmq2.cloudamqp.com
      username: lzufimom
      password: llcqxq_5XuJES-s0hhmiinhDfV3kVCDj

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/