server:
  port: 9003

spring:
  application:
    name: RIDE-SERVICE
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://bachelorproject-db.cxgz8qf6xo0i.eu-west-3.rds.amazonaws.com:3306/rides?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ride_service
    password: Hyf^*snE6tpyHVxcoeE3NsH4y
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9-mfnegy.eu.auth0.com/
  rabbitmq:
    external:
      host: rat.rmq2.cloudamqp.com
      username: iyopjwwd
      password: ntVEoqTWlN38mXwCrhgdHUmDaOwB86N1
    internal:
      host: rat.rmq2.cloudamqp.com
      username: lzufimom
      password: llcqxq_5XuJES-s0hhmiinhDfV3kVCDj

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/